"""empty message

Revision ID: 46db86018279
Revises: 917b6d7413a0
Create Date: 2023-05-17 18:33:25.919235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46db86018279'
down_revision = '917b6d7413a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_availability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=100), nullable=False),
    sa.Column('time_slot', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exclusion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profile.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exclusion')
    op.drop_table('provider_availability')
    # ### end Alembic commands ###
