"""empty message

Revision ID: abce36e1c681
Revises: b8c012d3e42e
Create Date: 2023-05-19 12:48:13.701267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abce36e1c681'
down_revision = 'b8c012d3e42e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_description',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('includes_consumables', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_provided',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profile.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service_description.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('service_list')
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('member_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('address_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'member_account', ['member_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('provider_availability', schema=None) as batch_op:
        batch_op.add_column(sa.Column('provider_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'provider_profile', ['provider_id'], ['id'])

    with op.batch_alter_table('provider_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_image', sa.String(), nullable=True))
        batch_op.drop_column('avatar_images')

    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('service_description_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'service_description', ['service_description_id'], ['id'])
        batch_op.drop_column('service')
        batch_op.drop_column('time_slot')

    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_image', sa.String(), nullable=True))
        batch_op.drop_column('avatar_images')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_images', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('avatar_image')

    with op.batch_alter_table('service_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_slot', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('service', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_description_id')
        batch_op.drop_column('time')

    with op.batch_alter_table('provider_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_images', sa.VARCHAR(), autoincrement=False, nullable=True))
        batch_op.drop_column('avatar_image')

    with op.batch_alter_table('provider_availability', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('provider_id')

    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('address_user_id_fkey', 'member_account', ['user_id'], ['id'])
        batch_op.drop_column('member_id')

    op.create_table('service_list',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('services_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profile.id'], name='service_list_provider_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='service_list_pkey')
    )
    op.drop_table('service_provided')
    op.drop_table('service_description')
    # ### end Alembic commands ###
