"""empty message

Revision ID: b8c012d3e42e
Revises: db85bcf95f2f
Create Date: 2023-05-18 18:16:56.370070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c012d3e42e'
down_revision = 'db85bcf95f2f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=True),
    sa.Column('services_name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['provider_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_list')
    # ### end Alembic commands ###
