"""empty message

Revision ID: db85bcf95f2f
Revises: 46db86018279
Create Date: 2023-05-18 18:15:53.973135

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db85bcf95f2f'
down_revision = '46db86018279'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_profile', schema=None) as batch_op:
        batch_op.drop_column('availability_binary_string')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('provider_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('availability_binary_string', sa.VARCHAR(length=21), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
