"""empty message

Revision ID: f50e7dad395e
Revises: 4c67af28f7b5
Create Date: 2023-05-19 19:42:07.684468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f50e7dad395e'
down_revision = '4c67af28f7b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_description', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_provided', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'service_provided', ['service_provided'], ['id'])

    with op.batch_alter_table('service_provided', schema=None) as batch_op:
        batch_op.drop_constraint('service_provided_service_id_fkey', type_='foreignkey')
        batch_op.drop_column('service_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_provided', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('service_provided_service_id_fkey', 'service_description', ['service_id'], ['id'])

    with op.batch_alter_table('service_description', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('service_provided')

    # ### end Alembic commands ###
